create schema identity;
create schema todo_app;


create table identity.users
(
    id           bigint generated by default as identity
        constraint users_pk primary key,
    first_name   varchar(70),
    last_name    varchar(70),
    expire_date timestamp,
    password_     varchar(70),
    remember_me  boolean,
    token        varchar(255),
    username     varchar(50)
);

create table identity.roles
(
    id    bigint generated by default as identity
        constraint roles_pk primary key,
    title varchar(50)
);

create table identity.users_roles
(
    id    bigint generated by default as identity
        constraint users_roles_pk primary key,

    user_id bigint not null
        constraint users_roles_user_id_fk
            references identity.users,
    role_id bigint not null
        constraint users_roles_role_id_fk
            references identity.roles

);

create table todo_app.tasks
(
    id      bigint generated by default as identity
        constraint tasks_pk  primary key,
    do_date timestamp,
    done    boolean not null default false,
    title   varchar(255),
    user_id bigint
        constraint tasks_user_id_fk
            references identity.users
);

insert into identity.roles (title) values('USER_ROLE')


