version: '3'
services:
  splunk:
    platform: linux/amd64
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
#      - SPLUNK_USER=admin
      - SPLUNK_PASSWORD=T%r4w2q1
      - SPLUNK_ROLE=splunk_search_head
      - SPLUNK_HTTP_PORT=8000
      - SPLUNK_CONNECTION_TIMEOUT=300
    ports:
      - "8000:8000"
      - "8088:8088"
    volumes:
      - ./splunk-data:/opt/splunk/var
    networks:
      - splunk_network

networks:
  splunk_network:
    driver: bridge